"""empty message

Revision ID: 001c56ab73d8
Revises: 86eb5029f1a3
Create Date: 2022-10-25 22:05:23.764730

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '001c56ab73d8'
down_revision = '86eb5029f1a3'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('traffic',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('repo_name', sa.String(length=80), nullable=False),
    sa.Column('clone_count', sa.Integer(), nullable=True),
    sa.Column('clone_count_unique', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['repo_name'], ['repos.name'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('traffic')
    # ### end Alembic commands ###
