"""empty message

Revision ID: 17c3644babff
Revises: 
Create Date: 2022-11-15 19:54:40.968816

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '17c3644babff'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('repos',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('name', sa.String(length=80), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_table('clone_history',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('repo_name', sa.String(length=80), nullable=True),
    sa.Column('timestamp', sa.DateTime(), nullable=False),
    sa.Column('clone_count', sa.Integer(), nullable=True),
    sa.Column('clone_count_unique', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['repo_name'], ['repos.name'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('timestamp', 'repo_name', name='_repo_timestamp_uc')
    )
    op.create_table('clone_summary',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('repo_name', sa.String(length=80), nullable=False),
    sa.Column('clone_count', sa.Integer(), nullable=True),
    sa.Column('clone_count_unique', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['repo_name'], ['repos.name'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('repo_name')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('clone_summary')
    op.drop_table('clone_history')
    op.drop_table('repos')
    # ### end Alembic commands ###
