"""Initial migration.

Revision ID: 37f6a139152b
Revises: 
Create Date: 2022-10-20 12:16:33.817758

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '37f6a139152b'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('clones')
    op.drop_table('traffic')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('traffic',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('repo', sa.VARCHAR(length=120), autoincrement=False, nullable=True),
    sa.Column('datetime', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.Column('clone_count', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('clone_count_unique', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('id', name='traffic_pkey')
    )
    op.create_table('clones',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('timestamp', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.Column('count', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('uniques', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('id', name='clones_pkey')
    )
    # ### end Alembic commands ###
