"""empty message

Revision ID: 6762ad95936a
Revises: 001c56ab73d8
Create Date: 2022-10-25 22:51:51.674403

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '6762ad95936a'
down_revision = '001c56ab73d8'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint(None, 'traffic', ['repo_name'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'traffic', type_='unique')
    # ### end Alembic commands ###
