"""empty message

Revision ID: 7338c29a85b8
Revises: 
Create Date: 2022-11-23 23:44:05.625764

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '7338c29a85b8'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('repo_views',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('repo_name', sa.String(length=200, collation=ForeignKey('repos.name')), nullable=True),
    sa.Column('view_count', sa.Integer(), nullable=True),
    sa.Column('view_count_unique', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('repos',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_table('clone_history',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('repo_name', sa.String(length=200), nullable=True),
    sa.Column('timestamp', sa.DateTime(), nullable=False),
    sa.Column('clone_count', sa.Integer(), nullable=True),
    sa.Column('clone_count_unique', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['repo_name'], ['repos.name'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('timestamp', 'repo_name', name='_repo_timestamp_uc')
    )
    op.create_table('clone_summary',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('repo_name', sa.String(length=200), nullable=False),
    sa.Column('clone_count', sa.Integer(), nullable=True),
    sa.Column('clone_count_unique', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['repo_name'], ['repos.name'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('repo_name')
    )
    op.create_table('ref_paths',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('repo_name', sa.String(length=200), nullable=True),
    sa.Column('path', sa.String(length=200), nullable=True),
    sa.Column('title', sa.String(length=200), nullable=True),
    sa.Column('count', sa.Integer(), nullable=True),
    sa.Column('unique', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['repo_name'], ['repos.name'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('repo_name', 'path', name='_repo_path_uc')
    )
    op.create_table('ref_sources',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('repo_name', sa.String(length=200), nullable=True),
    sa.Column('source', sa.String(length=200), nullable=True),
    sa.Column('count', sa.Integer(), nullable=True),
    sa.Column('unique', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['repo_name'], ['repos.name'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('repo_name', 'source', name='_repo_source_uc')
    )
    op.create_table('repo_views_history',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('repo_name', sa.String(length=200), nullable=True),
    sa.Column('timestamp', sa.DateTime(), nullable=False),
    sa.Column('view_count', sa.Integer(), nullable=True),
    sa.Column('view_count_unique', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['repo_name'], ['repos.name'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('timestamp', 'repo_name', name='_repo_view_timestamp_uc')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('repo_views_history')
    op.drop_table('ref_sources')
    op.drop_table('ref_paths')
    op.drop_table('clone_summary')
    op.drop_table('clone_history')
    op.drop_table('repos')
    op.drop_table('repo_views')
    # ### end Alembic commands ###
