"""db views

Revision ID: dd66d437cc20
Revises: 17c3644babff
Create Date: 2022-11-23 21:46:04.824300

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'dd66d437cc20'
down_revision = '17c3644babff'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('repo_views',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('repo_name', sa.String(length=80), nullable=True),
    sa.Column('view_count', sa.Integer(), nullable=True),
    sa.Column('view_count_unique', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['repo_name'], ['repos.name'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('repo_views_history',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('repo_name', sa.String(length=80), nullable=True),
    sa.Column('timestamp', sa.DateTime(), nullable=False),
    sa.Column('view_count', sa.Integer(), nullable=True),
    sa.Column('view_count_unique', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['repo_name'], ['repos.name'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('timestamp', 'repo_name', name='_repo_timestamp_uc')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('repo_views_history')
    op.drop_table('repo_views')
    # ### end Alembic commands ###
