"""Traffic

Revision ID: fc9878e13060
Revises: bd58f3c7c846
Create Date: 2022-10-20 12:38:00.440210

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'fc9878e13060'
down_revision = 'bd58f3c7c846'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('traffic',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('repo_id', sa.Integer(), nullable=False),
    sa.Column('clone_count', sa.Integer(), nullable=True),
    sa.Column('clone_count_unique', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['repo_id'], ['repos.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.drop_column('repos', 'name')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('repos', sa.Column('name', sa.VARCHAR(length=150), autoincrement=False, nullable=True))
    op.drop_table('traffic')
    # ### end Alembic commands ###
